#ifndef _SETTINGS_H
#define _SETTINGS_H

#define DEBUG_MODE 1

#define LED_COUNT    3 
#define LED_PIN     D2
#define BUTTON_PIN  D1
#define BUTTONLOW_PIN D0
#define SERVO_PIN D6

#define MAX_OSCILLATION_DURATION 500
#define MATRIX_CS_PIN D8
#define LED_MATRIX_BRIGHTNESS 6

#define FADEIN_DELAY 5
#define FADEOUT_DELAY 8

#define REQUEST_DELAY 1000
#define FIRMWARE_VERSION 3

#endif
